export enum GroovyTokenId {
	CompilationUnit,
	// whitespace, tabs and newline
	Whitespaces,
	Tabs,
	Newline,
	// bracket
	LBrace,
	RBrace,
	LBrack,
	RBrack,
	LParen,
	RParen,
	LAngle,
	RAngle,
	// symbol
	Slash,
	Backslash,
	Tilde,
	At,
	Hash,
	Dollar,
	Percent,
	Exponent,
	And,
	Asterisk,
	Question,
	Minus,
	Plus,
	Equal,
	Underscore,
	Pipe,
	Quote,
	DblQuote,
	BackQuote,
	Dot,
	Comma,
	Colon,
	Semicolon,
	// literal
	// number literal
	BinaryLiteral,
	BinaryStartMark,
	OctalLiteral,
	OctalStartMark,
	IntegerLiteral,
	HexadecimalLiteral,
	HexadecimalStartMark,
	DecimalLiteral,
	Numbers,
	NumberSeparators,
	NumberDecimalPoint,
	NumberExponent,
	NumberExponentStartMark,
	NumberExponentSign,
	NumberSuffix,
	// string literal
	/** single quote string literal */ SsqSLiteral,
	/** single quote string literal mark */ SsqSLMark,
	/** triple quotes string literal */ TsqSLiteral,
	/** triple quotes string literal mark */ TsqSLMark,
	/** single double-quotes gstring literal */ SdqGsLiteral,
	/** single double-quotes gstring literal mark */ SdqGsLMark,
	/** triple double-quotes gstring literal */ TdqGsLiteral,
	/** triple double-quotes gstring literal mark */ TdqGsLMark,
	/** slashy gstring literal */ SGsLiteral,
	/** slashy gstring literal mark */ SGsLMark,
	/** dollar slashy gstring literal */ DsGsLiteral,
	/** dollar slashy gstring literal start mark */ DsGsLStartMark,
	/** dollar slashy gstring literal end mark */ DsGsLEndMark,
	BackspaceEscape,
	FormFeedEscape,
	NewlineEscape,
	CarriageReturnEscape,
	TabulationEscape,
	BackslashEscape,
	SingleQuoteEscape,
	DoubleQuotesEscape,
	/** \$ for all quote string literals, $$ for slashy dollar gstring literal */ DollarEscape,
	/** \/ for slashy gstring literals, $/ for slashy dollar gstring literal */ SlashEscape,
	OctalEscape,
	OctalEscapeStartMark,
	OctalEscapeContent,
	UnicodeEscape,
	UnicodeEscapeStartMark,
	UnicodeEscapeContent,
	BadEscape,
	/** newline eraser for multiple-lines string/gstring */ MLSNewlineEraser,
	/** gstring interpolation */ GsInterpolation,
	/** gstring interpolation start mark, $ */ GsiStartMark,
	/** gstring interpolation start mark, ${ */ GsiBraceStartMark,
	/** gstring interpolation end mark, } */ GsiBraceEndMark,
	// chars
	Word,
	UndeterminedChar,
	// shebang
	Shebang,
	ShebangStartMark,
	// comment
	SLComment,
	SLCommentStartMark,
	MLComment,
	MLCommentStartMark,
	MLCommentEndMark,
}

export const T = GroovyTokenId;
