export enum GroovyTokenId {
	CompilationUnit,
	// whitespace, tabs and newline
	Whitespaces,
	Tabs,
	Newline,
	// bracket
	LBrace,
	RBrace,
	LBrack,
	RBrack,
	LParen,
	RParen,
	LAngle,
	RAngle,
	// symbol
	Slash,
	Backslash,
	Tilde,
	At,
	Hash,
	Dollar,
	Percent,
	Exponent,
	And,
	Asterisk,
	Question,
	Minus,
	Plus,
	Equal,
	Underscore,
	Pipe,
	Quote,
	DblQuote,
	BackQuote,
	Dot,
	Comma,
	Colon,
	Semicolon,
	// literal
	// number literal
	BinaryLiteral,
	BinaryStartMark,
	OctalLiteral,
	OctalStartMark,
	IntegerLiteral,
	HexadecimalLiteral,
	HexadecimalStartMark,
	DecimalLiteral,
	Numbers,
	NumberSeparators,
	NumberDecimalPoint,
	NumberExponent,
	NumberExponentStartMark,
	NumberExponentSign,
	NumberSuffix,
	// string literal
	/** single quote string literal */ SsqSLiteral,
	SsqSLMark,
	/** triple quotes string literal */ TsqSLiteral,
	TsqSLMark,
	/** single double-quotes gstring literal */ SdqGsLiteral,
	SdqGsLMark,
	/** triple double-quotes gstring literal */ TdqGsLiteral,
	TdqGsLMark,
	/** slashy gstring literal */ SGsLiteral,
	SGsLMark,
	/** dollar slashy gstring literal */ DsGsLiteral,
	DsGsLStartMark,
	DsGsLEndMark,
	BackspaceEscape,
	FormFeedEscape,
	NewlineEscape,
	CarriageReturnEscape,
	TabulationEscape,
	BackslashEscape,
	SingleQuoteEscape,
	DoubleQuotesEscape,
	DollarEscape,
	SlashEscape,
	DoubleDollarsEscape,
	OctalEscape,
	UnicodeEscape,
	// chars
	Word,
	UndeterminedChar,
	// shebang
	Shebang,
	ShebangStartMark,
	// comment
	SLComment,
	SLCommentStartMark,
	MLComment,
	MLCommentStartMark,
	MLCommentEndMark,
}

export const T = GroovyTokenId;
