export const KeywordPatterns = {
	// groovy keywords
	AS: 'as',
	DEF: 'def',
	TRAIT: 'trait',
	THREADSAFE: '@ThreadSafe;fn#NotJNamePart:!',
	// java keywords
	ABSTRACT: 'abstract',
	ASSERT: 'assert',
	AT_INTERFACE: '@interface;fn#NotJNamePart:!',
	BREAK: 'break',
	CASE: 'case',
	CATCH: 'catch',
	CLASS: 'class',
	CONST: 'const',
	CONTINUE: 'continue',
	DEFAULT: 'default',
	DO: 'do',
	ELSE: 'else',
	ENUM: 'enum',
	EXTENDS: 'extends',
	FINAL: 'final',
	FINALLY: 'finally',
	FOR: 'for',
	GOTO: 'goto',
	IF: 'if',
	IMPLEMENTS: 'implements',
	IMPORT: 'import',
	INTERFACE: 'interface',
	NATIVE: 'native',
	NEW: 'new',
	NON_SEALED: 'non-sealed',
	NULL: 'null',
	PACKAGE: 'package',
	PERMITS: 'permits',
	PRIVATE: 'private',
	PROTECTED: 'protected',
	PUBLIC: 'public',
	RECORD: 'record',
	RETURN: 'return',
	SEALED: 'sealed',
	STATIC: 'static',
	STRICTFP: 'strictfp',
	SUPER: 'super',
	SWITCH: 'switch',
	SYNCHRONIZED: 'synchronized',
	THIS: 'this',
	THROW: 'throw',
	THROWS: 'throws',
	TRANSIENT: 'transient',
	TRY: 'try',
	VAR: 'var',
	VOID: 'void',
	VOLATILE: 'volatile',
	WHILE: 'while',
	YIELD: 'yield'
};

// export const KeywordTokenMatchers = buildTokenMatchers(KeywordPatterns);
